CREATE TABLE AIRLINE
(
   CODE INT NOT NULL CONSTRAINT pk_airline PRIMARY KEY,
	 NAME VARCHAR(30),
	 COUNTRY VARCHAR(30)
);

CREATE TABLE BOOKING
(
	CODE INT NOT NULL CONSTRAINT pk_booking PRIMARY KEY,
	AGENCY VARCHAR(50),
	AIRLINE_CODE INT,
	FLIGHT_NUMBER INT,
	CUSTOMER_ID INT,
	BOOKING_DATE DATE,
	FLIGHT_DATE DATE,
	FLIGHT_DURATION INT,
	AIRPLANE VARCHAR(30)
);

CREATE TABLE AGENCY
(
	NAME VARCHAR(30),
	COUNTRY VARCHAR(30),
	CITY VARCHAR(30),
	PHONE CHAR(10) NOT NULL CONSTRAINT pk_phone PRIMARY KEY
);

CREATE TABLE AIRPORT
(
	CODE INT NOT NULL CONSTRAINT pk_airport PRIMARY KEY,
	NAME VARCHAR(30),
	COUNTRY VARCHAR(30),
	CITY VARCHAR(30)
);

CREATE TABLE CUSTOMER
(
	ID INT NOT NULL CONSTRAINT pk_customer PRIMARY KEY,
	FNAME VARCHAR(30),
	LNAME VARCHAR(30),
	EMAIL VARCHAR(30)
);

CREATE TABLE FLIGHT
(
	FNUMBER INT NOT NULL CONSTRAINT pk_flight PRIMARY KEY,
	AIRLINE_OPERATOR VARCHAR(30),
	DEP_AIRPORT VARCHAR(30),
	ARR_AIRPORT VARCHAR(30),
	FLIGHT_TIME DATETIME,
	FLIGHT_DURATION INT,
	AIRPLANE VARCHAR(30)
);
